spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sisdvac_db
    username: postgres
    password: )7L}g$d&cP!)w)h
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false # change to true when testing
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  servlet:
    context-path: /sisdvac
  port: 5000

application:
  security:
    jwt:
      secret-key: 472B4B6250655368566B5970337336763979244226452948404D635166546A57
      expiration: 600000 # 10 minutes
      refresh-token:
        expiration: 604800000 # 7 days

logging:
  level:
    root: info